### ISSUE TITLE
Zerodha API - Trade Signals are not fired

### ISSUE THREAD

**Issue by arjun-k-r** [sreenivasdoosa/sdoosa-algo-trade-app#15]
FYI..
I am using Zerodha API, Login in everything works file and stocks scanned with VWAP are saved sucessfully in trade_signals.json. but trade  signals are not fired.

when i run the code , trade_signals.json file have 2 stocks.
But they are not triggered and does not show in trades.json file.

.below is the only error i got in log file

INFO | VWAP: BIOCON: prev day data = {"date":"2021-02-08T18:30:00.000Z","open":409,"high":409.95,"low":402.8,"close":404.8,"volume":3195358,"timestamp":"2021-02-08T18:30:00.000Z"}
(node:4900) UnhandledPromiseRejectionWarning: Error: Callback was already called.
    at D:\WORK\FIRETICK\node_modules\async\dist\async.js:966:32
    at D:\WORK\FIRETICK\node_modules\async\dist\async.js:3885:13
    at D:\WORK\FIRETICK\dist\server\strategies\BaseStrategy.js:470:15
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
(node:4900) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4900) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Kindly help me to resolve this issue.

**Comment by arjun-k-r** [comment]
@sreenivasdoosa @meetmeoften @praneet1984

**Comment by pulivarthi123** [comment]
Any update on this. Trade signals generated and saved to file but Trades not generated / saved / triggered  or no error - Broker Zerodha
