### ISSUE TITLE
Fixed issue of code not working in version greater than Node 11

### ISSUE THREAD

**Issue by praneeth1984** [sreenivasdoosa/sdoosa-algo-trade-app#7]
Hello,

First of all, thanks a ton for this amazing framework. 

I had node 12 version in my laptop and I did not want to downgrade to Node 11. I found out the code node not working on higher version of Node is due to Gulp using an older version which is not compatible with Node 12 or higher.

The fix for this is here in this link https://ourcodeworld.com/articles/read/1188/how-to-solve-gulp-exception-reference-error-primordials-is-not-defined-error .

I tried and it works fine for me. I hope this helps others too.

Praneeth

**Comment by suresh-n** [comment]
that helped. but i see another error is this expected. ??

(node:9732) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'instrument_token' of undefined
    at Instruments.getInstrumentToken (C:\Users\test\SN\sdoosa-algo-trade-app\dist\server\brokers\zerodha\Instruments.js:36:25)
    at ZerodhaHistoryAPIs.fetchHistory (C:\Users\test\SN\sdoosa-algo-trade-app\dist\server\brokers\zerodha\ZerodhaHistoryAPIs.js:60:43)
    at HistoryAPIs.fetchHistory (C:\Users\test\SN\sdoosa-algo-trade-app\dist\server\core\HistoryAPIs.js:56:49)
    at C:\Users\test\SN\sdoosa-algo-trade-app\dist\server\strategies\BaseStrategy.js:431:37
    at C:\Users\test\SN\sdoosa-algo-trade-app\node_modules\async\dist\async.js:3880:24
    at replenish (C:\Users\test\SN\sdoosa-algo-trade-app\node_modules\async\dist\async.js:1011:17)
    at iterateeCallback (C:\Users\test\SN\sdoosa-algo-trade-app\node_modules\async\dist\async.js:995:17)
    at C:\Users\test\SN\sdoosa-algo-trade-app\node_modules\async\dist\async.js:969:16
    at C:\Users\test\SN\sdoosa-algo-trade-app\node_modules\async\dist\async.js:3885:13
    at C:\Users\test\SN\sdoosa-algo-trade-app\dist\server\strategies\BaseStrategy.js:468:15
    at processTicksAndRejections (internal/process/task_queues.js:88:5)
(node:9732) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 39)
(node:9732) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by suresh-n** [comment]
this fixed after i subscribed for historical API.

**Comment by praneeth1984** [comment]
> this fixed after i subscribed for historical API.

I just saw your message. I hope the issue got fixed.

**Comment by jani77996** [comment]
> Hello,
> 
> First of all, thanks a ton for this amazing framework.
> 
> I had node 12 version in my laptop and I did not want to downgrade to Node 11. I found out the code node not working on higher version of Node is due to Gulp using an older version which is not compatible with Node 12 or higher.
> 
> The fix for this is here in this link https://ourcodeworld.com/articles/read/1188/how-to-solve-gulp-exception-reference-error-primordials-is-not-defined-error .
> 
> I tried and it works fine for me. I hope this helps others too.
> 
> Praneeth

Hi praneeth
 I have node 14th verstion what can i do
There is some npm issue
